import { z } from "zod";
import { fileURLToPath } from "node:url";
import type { CommandDef } from "citty";
import { defineTool } from "../tool.ts";
import { loadCommands } from "../discover.ts";
import { buildCatalog, type CatalogEnv, type CatalogNode } from "../catalog.ts";
import { log } from "../core/log.ts";

export default defineTool({
  summary:
    "Emit the full command catalog (the machine-readable tool manifest for LLMs), or regenerate .env.example / AGENTS.md.",
  when: "Use to discover every tool, its args, WHEN to call it, and its required env — in one machine-readable payload.",
  kind: "query",
  input: z.object({
    path: z.string().optional().describe("Scope to a subtree, e.g. 'search rentcast'"),
    format: z.enum(["json", "env-example", "agents"]).default("json").describe("Output format"),
  }),
  async run({ input }) {
    const commandsDir = fileURLToPath(new URL("./", import.meta.url));
    const root: CommandDef = { meta: { name: "housing" }, subCommands: loadCommands(commandsDir) };
    let catalog = await buildCatalog(root);
    if (input.path) {
      const parts = input.path.split(/[.\s]+/).filter(Boolean);
      catalog = scope(catalog, parts) ?? catalog;
    }
    if (input.format === "env-example") log.out(renderEnvExample(catalog));
    else if (input.format === "agents") log.out(renderAgents(catalog));
    else log.out(JSON.stringify(catalog, null, 2));
  },
});

function scope(node: CatalogNode, parts: string[]): CatalogNode | null {
  if (parts.length === 0) return node;
  const [head, ...rest] = parts;
  const child = node.children?.find((c) => c.path[c.path.length - 1] === head);
  return child ? scope(child, rest) : null;
}

function collectEnv(
  node: CatalogNode,
  acc = new Map<string, CatalogEnv>(),
): Map<string, CatalogEnv> {
  for (const e of node.requires ?? []) if (!acc.has(e.key)) acc.set(e.key, e);
  for (const c of node.children ?? []) collectEnv(c, acc);
  return acc;
}

function renderEnvExample(catalog: CatalogNode): string {
  const env = [...collectEnv(catalog).values()].sort((a, b) => a.key.localeCompare(b.key));
  const lines = [
    "# Generated by `housing introspect --format env-example`. Copy to .env and fill in.",
    "# The no-auth sources run on an empty .env; keys below only unlock extra sources/features.",
    "",
  ];
  for (const e of env) {
    const where = e.getAt ? ` — ${e.getAt}` : "";
    lines.push(`# ${e.description}${where}${e.required ? " (required)" : " (optional)"}`);
    lines.push(`# ${e.key}=`);
    lines.push("");
  }
  return lines.join("\n");
}

function renderAgents(catalog: CatalogNode): string {
  const lines = [
    "# housing — agent tool catalog",
    "",
    "Generated by `housing introspect --format agents`. Do not hand-edit.",
    "",
    "Invoke a tool: `mise run housing -- <command> [flags]` (or `./housing <command>`).",
    "Full machine-readable manifest: `housing introspect --json`.",
    "",
  ];
  const walk = (node: CatalogNode): void => {
    if (node.kind !== "group" && node.summary) {
      lines.push(`## \`${node.argv}\`  _(${node.kind})_`);
      lines.push(node.summary);
      if (node.when) lines.push(`- **When:** ${node.when}`);
      if (node.args?.length)
        lines.push(
          `- **Args:** ${node.args.map((a) => `--${a.name}${a.required ? "*" : ""}`).join(", ")}`,
        );
      if (node.requires?.length)
        lines.push(
          `- **Env:** ${node.requires.map((r) => r.key + (r.required ? "*" : "")).join(", ")}`,
        );
      if (node.examples?.length) lines.push(`- **Example:** \`${node.examples[0]}\``);
      lines.push("");
    }
    for (const c of node.children ?? []) walk(c);
  };
  walk(catalog);
  lines.push("_`*` = required._");
  return lines.join("\n");
}
